HospitalMVCItCloud/Models/Classes/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HospitalMVCItCloud.Models.Classes
{
    public partial class Doctor
    {
        public Doctor()
        {
            Patients = new HashSet<Patient>();
        }
        public int Id { get; set; }

        public string Name { get; set; }

        public int SpecializationId { get; set; }

        public virtual Specialization Specialization { get; set; }

        public virtual ICollection<Patient> Patients { get; set; }
    }
}

HospitalMVCItCloud/Models/DoctorViewModel.cs
using HospitalMVCItCloud.Models.Classes;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HospitalMVCItCloud.Models
{
    public class DoctorViewModel
    {
        public Doctor Doctor { get; set; }
        public IEnumerable<SelectListItem> AllPatients { get; set; }

        private List<int> _selectedPatients;
        public List<int> SelectedPatients
        {
            get
            {
                if (_selectedPatients == null)
                {
                    _selectedPatients = Doctor.Patients.Select(m => m.Id).ToList();
                }
                return _selectedPatients;
            }
            set { _selectedPatients = value; }
        }
    }
}

HospitalMVCItCloud/Controllers/DoctorsController.cs
using HospitalMVCItCloud.Dal;
using HospitalMVCItCloud.Models;
using HospitalMVCItCloud.Models.Classes;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HospitalMVCItCloud.Controllers
{
    [Authorize(Roles = "Admin, Moderator")]
    public class DoctorsController : Controller
    {
        private readonly HospitalContext db = new HospitalContext();

        // GET: /Doctors/
        [Authorize(Roles = "Admin, Moderator,Doctor")]
        public ActionResult Index(string searchname)
        {
            var doctors = db.Doctors.Include(j => j.Specialization);
            return View(doctors.Where(p => p.Name.ToLower().Contains(searchname.ToLower()) || searchname == null).ToList());
        }

        // GET: Doctors/Details/5
        [Authorize(Roles = "Admin, Moderator,Doctor")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: /Doctor/Create
        public ActionResult Create()
        {
            ViewBag.SpecializationID = new SelectList(db.Specializations, "Id", "Name");
            return View();
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,SpecializationId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SpecializationID = new SelectList(db.Specializations, "Id", "Name", doctor.SpecializationId);
            return View(doctor);
        }


        // GET: /Doctor/Edit/5
        [Authorize(Roles = "Admin, Moderator,Doctor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var doctorViewModel = new DoctorViewModel
            {
                Doctor = db.Doctors.Include(i => i.Patients).First(i => i.Id == id)
            };

            if (doctorViewModel.Doctor == null)
                return HttpNotFound();
            var allPatientsList = db.Patients.ToList();

            doctorViewModel.AllPatients = allPatientsList.Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString()
            });

            ViewBag.SpecializationID = new SelectList(db.Specializations, "Id", "Name", doctorViewModel.Doctor.SpecializationId);
            return View(doctorViewModel);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Moderator,Doctor")]
        [HttpPost]
        [ValidateAntiForgeryToken]//[Bind(Include = "Name,Id,SpecializationID,SelectedPatients")]
        public ActionResult Edit(DoctorViewModel doctorView)
        {
            if (doctorView == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (ModelState.IsValid)
            {
                var docUpdate = db.Doctors
                    .Include(i => i.Patients).First(i => i.Id == doctorView.Doctor.Id);

                if (TryUpdateModel(docUpdate, "Doctor", new string[] { "Name", "SpecializationID" }))
                {
                    var newPatients = db.Patients.Where(
                        p => doctorView.SelectedPatients.Contains(p.Id)).ToList();
                    var updatedPatients = new HashSet<int>(doctorView.SelectedPatients);
                    foreach (Patient patient in db.Patients)
                    {
                        if (!updatedPatients.Contains(patient.Id))
                        {
                            docUpdate.Patients.Remove(patient);
                        }
                        else
                        {
                            docUpdate.Patients.Add((patient));
                        }
                    }
                    
                    db.Entry(docUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            ViewBag.SpecializationID = new SelectList(db.Specializations, "Id", "Name", doctorView.Doctor.SpecializationId);
            return View(doctorView);
        }

        // GET: /Doctor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Doctor doctor = db.Doctors
                .Include(j => j.Patients)
                .First(j => j.Id == id);

            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors
                 .Include(j => j.Patients)
                 .First(j => j.Id == id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalMVCItCloud/Views/Doctors/Create.cshtml
@model HospitalMVCItCloud.Models.Classes.Doctor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecializationId, "SpecializationId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecializationId", String.Empty)
                @Html.ValidationMessageFor(model => model.SpecializationId)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Patients, "Patients", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Patients", String.Empty)
                @Html.ValidationMessageFor(model => model.Patients)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMVCItCloud/Views/Doctors/Delete.cshtml
@model HospitalMVCItCloud.Models.Classes.Doctor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecializationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecializationId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalMVCItCloud/Views/Doctors/Details.cshtml
@model HospitalMVCItCloud.Models.Classes.Doctor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecializationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecializationId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalMVCItCloud/Views/Doctors/Edit.cshtml
@model HospitalMVCItCloud.Models.DoctorViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Doctor.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doctor.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor.SpecializationId, "SpecializationId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(m => m.Doctor.SpecializationId,
                        (SelectList)ViewBag.SpecializationId,
                        Model.Doctor.Specialization.Id);

                @Html.ValidationMessageFor(model => model.Doctor.SpecializationId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AllPatients, "Patients", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedPatients, Model.AllPatients)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMVCItCloud/Views/Doctors/Index.cshtml
@model IEnumerable<HospitalMVCItCloud.Models.Classes.Doctor>

@{
    ViewBag.Title = "Index";
}

<h2>Doctor</h2>
@using (Html.BeginForm("Index", "Doctors", "Index"))
{
    <div class="form-group">
        <input class="form-control" type="text" name="searchname" placeholder="Search" label="Search">
        <input type="submit" value="Search" />
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpecializationId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patients)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Specialization.Name)
        </td>
        <td>
            @Html.ListBox("Id", new SelectList(item.Patients, "Id", "Name"))
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}